- config/prooph.php
- config/routes.php
- config/services.php
- src/App/Commanding/API.php
- src/Container/Model/Todo/PostTodoHandlerFactory.php
- src/Container/Model/User/RegisterUserHandlerFactory.php
- src/Model/Todo/Command/PostTodo.php
- src/Model/Todo/Event/TodoWasPosted.php
- src/Model/Todo/Exception/InvalidText.php
- src/Model/Todo/Exception/TodoAlreadyDone.php
- src/Model/Todo/Handler/PostTodoHandler.php
- src/Model/Todo/Todo.php
- src/Model/User/Command/RegisterUser.php
- src/Model/User/Event/UserWasRegistered.php
- src/Model/User/Exception/InvalidName.php
- src/Model/User/Exception/UserNotFound.php
- src/Model/User/Handler/RegisterUserHandler.php
- src/Model/User/User.php
- src/Projection/Todo/TodoProjector.php
- src/Projection/User/UserProjector.php
see: https://github.com/prooph/proophessor-do/issues/13
> Clean up model dir

- config/event_store.local.php.dist
- config/mongo_client.local.php.dist
- config/services.php
- docs/installation.md
> Move mongo client factory into own config file

- docs/installation.md
- src/App/Commanding/API.php
Workaround for #11 
We will add a real error handler at a later stage.
> Send error messages only in development mode

- config/prooph.php
- config/routes.php
- config/services.php
- public/css/style.css
- src/Container/Model/Todo/MarkTodoAsDoneHandlerFactory.php
- src/Model/Todo/Command/MarkTodoAsDone.php
- src/Model/Todo/Event/TodoWasMarkedAsDone.php
- src/Model/Todo/Exception/TodoNotOpen.php
- src/Model/Todo/Handler/MarkTodoAsDoneHandler.php
- src/Model/Todo/Todo.php
- src/Projection/Todo/TodoProjector.php
- tests/Model/Todo/TodoTest.php
- view/action/user-todo-list.phtml
> Add Mark a todo as done functionality

- composer.json
> Remove unused bin-dir config

- src/Model/Todo/Exception/TodoNotOpen.php
- src/Model/Todo/Todo.php
- tests/Model/Todo/TodoTest.php
@codeliner Implements #39, please review.
> Validate, if the status of todo is not done, before recording the deadline

- bin/setup_mongodb.sh
> No migrations for mongodb.

- .coveralls.yml
- .travis.yml
- composer.json
> Bump coveralls version to 1.0

- README.md
Suggestion for an advanced DIY feature
> Suggests an advanced DIY feature

- docker-compose.yml
- docs/installation.md
Follow up to https://github.com/prooph/proophessor-do/pull/66
Changed branch. I hope this is alright now. I am pretty new to this contributing thing.
> Updated docker docs (php7 image and event store adapter)

- config/config.php
> Remove else

- docs/installation.md
> Update first step of Docker installation instructions to include down load of source code

- scripts/add_deadlines.php
The script was broken since the dbal connection fetch mode has been changed here https://github.com/prooph/proophessor-do/commit/a0208f7a2906d6ab8ed53d797ec69dfe241adec6#diff-066a62d37628147c1e68cb5afff96f7eR36
> Fix add deadlines script

- config/autoload/dependencies.global.php
- config/autoload/prooph.global.php
- config/autoload/prooph_dependencies.global.php
- src/App/Action/UserList.php
- src/App/Action/UserTodoForm.php
- src/App/Action/UserTodoList.php
- src/App/Mail/SendTodoReminderMailSubscriber.php
- src/Container/App/Action/UserListFactory.php
- src/Container/App/Action/UserTodoFormFactory.php
- src/Container/App/Action/UserTodoListFactory.php
- src/Container/App/Mail/SendTodoReminderMailSubscriberFactory.php
- src/Container/Model/Todo/GetTodoByIdHandlerFactory.php
- src/Container/Model/Todo/GetTodosByAssigneeIdHandlerFactory.php
- src/Container/Model/User/GetAllUsersHandlerFactory.php
- src/Container/Model/User/GetUserByIdHandlerFactory.php
- src/Model/Todo/Handler/GetTodoByIdHandler.php
- src/Model/Todo/Handler/GetTodosByAssigneeIdHandler.php
- src/Model/Todo/Query/GetTodoById.php
- src/Model/Todo/Query/GetTodosByAssigneeId.php
- src/Model/User/Handler/GetAllUsersHandler.php
- src/Model/User/Handler/GetUserByIdHandler.php
- src/Model/User/Query/GetAllUsers.php
- src/Model/User/Query/GetUserById.php
> Use QueryBus

- src/Model/User/Handler/RegisterUserHandler.php
> solve parse error for php 5.6

- bin/migrations.php
- composer.json
DialogHelper is deprecated. 
Fixes #103
> Change DialogHelper to QuestionHelper

- tests/Model/Todo/Command/AddReminderToTodoTest.php
> 'Add reminder' doesn't work fix

- docker-compose.yml
- docs/installation/docker.md
Also enable dev mode by default for docker set up.
> Add some hints regarding docker DB config

- Vagrantfile
- docs/installation/vagrant.md
Some adjustments to vagrant setup method
> Vagrant config adjust

- Vagrantfile
I had a strange entropy bug with Docker and php 7.1.2 (https://github.com/docker-library/php/issues/376)
This will also be fixed by PHP 7.1.4 but using a newer Ubuntu cant be wrong since it
has much better docker support.
> Bump vagrant base box 

- README.md
- docs/installation/debugging.md
- docs/installation/index.md
Dont know if useful - let me know.
> Add debugging section to docs

- docs/installation/manual.md
while debugging issue #144, I found several sql-schema-files for MariaDB, MySQL and Postgres.
> Custom SQL files for different database systems

- config/autoload/mariadb_event_store.local.php.dist
- config/autoload/prooph_dependencies.global.php
See #146 - the mongodb configuration file is missing and added like mysql & Postgres.
> Added MariaDB Configuration File

- composer.json
- composer.lock
- src/App/Action/Home.php
- src/App/Action/UserList.php
- src/App/Action/UserRegistration.php
- src/App/Action/UserTodoForm.php
- src/App/Action/UserTodoList.php
- src/Middleware/JsonPayload.php
- tests/App/Action/HomeTest.php
> Http middleware downgrade

- scripts/add_deadlines.php
- scripts/load_todo_with_snapshot.php
- scripts/load_todo_without_snapshot.php
- scripts/take_todo_snapshot.php
- scripts/user_todo_open_close.php
AggregateType and SnapshotStore were moved to another namespace
> Fix scripts
